### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by pwz2k** [FutureHndrxxx/futurehndrxxx.github.io#1]
Who is running this joint? This can't be serious right? Because if it is serious then you're 100% going about this coin all the wrong way. Nobody will ever notice it. You need to contact me so we can discuss if you're trying to be serious. As it appears you have no idea what you're doing with getting exposure.

**Comment by FutureHndrxxx** [comment]
Looking at your profile history you have done nothing but open similar issues on 25 different repos lol someone wants to boost their "influencer" business and insulting people you want as potential customers is a poor way to go to about it for future reference.

Finally to answer your question - of course this is a joke, read the website. It is literally listed as a "shitcoin" and a "memecoin."

**Comment by pwz2k** [comment]
I understand it's a memecoin. However, you're missing the point and too busy take offense to the truth. You paid $626 to deploy it. If you wanted some sort of traction, you went about it the wrong way with this specific coin.  If you want assistance you know how to reach me.
